version: '3.9'

services:
  vulnforum:
    build: .
    container_name: vulnforum
    ports:
      - "5000:5000"
    volumes:
      - .:/app                  # hot-reload кода (меняешь файлы — сразу видно)
      - db_data:/app            # БД сохраняется между перезапусками
    restart: unless-stopped
    environment:
      - FLASK_ENV=development

volumes:
  db_data: