services:
  vulnforum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vulnforum
    ports:
      - "5000:5000"
    volumes:
      - .:/app                  
      - db_data:/app            
    restart: unless-stopped
    environment:
      - FLASK_ENV=development

volumes:
  db_data: