services:
  vulnforum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vulnforum
    ports:
      - "80:80"
    volumes:
      - .:/app                  
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=80

volumes:
  db_data: